#!/usr/bin/env python3
"""
3D B-field Visualization with PyVista

Loads VTK data generated by the Rust example and creates an interactive
3D visualization with streamlines, color-coded field magnitude, and magnet geometry.

Requirements:
    pip install pyvista numpy

Usage:
    python3 visualize_3d.py
"""

import pyvista as pv
import numpy as np

# Load the VTK file
print("Loading VTK data...")
mesh = pv.read('bfield_3d.vtk')

print(f"Data loaded successfully!")
print(f"  Grid dimensions: {mesh.dimensions}")
print(f"  Number of points: {mesh.n_points}")
print(f"  Number of cells: {mesh.n_cells}")
print(f"  Field arrays: {mesh.array_names}")

# Get B-field magnitude for color mapping
b_vectors = mesh['B']
b_magnitude = np.linalg.norm(b_vectors, axis=1)
mesh['B_magnitude'] = b_magnitude

print(f"\nField magnitude statistics:")
print(f"  Min: {b_magnitude.min():.3e} T")
print(f"  Max: {b_magnitude.max():.3e} T")
print(f"  Mean: {b_magnitude.mean():.3e} T")
print(f"  Median: {np.median(b_magnitude):.3e} T")

# Create visualization
print("\nGenerating 3D visualization...")
plotter = pv.Plotter()
plotter.set_background('white')

# Define magnet geometry (cuboid: 10mm x 10mm x 4mm centered at origin)
magnet_bounds = np.array([
    [-0.005, 0.005],  # x: -5mm to +5mm
    [-0.005, 0.005],  # y: -5mm to +5mm
    [-0.002, 0.002],  # z: -2mm to +2mm
])

# Create magnet mesh
magnet_mesh = pv.Box(bounds=[
    magnet_bounds[0, 0], magnet_bounds[0, 1],
    magnet_bounds[1, 0], magnet_bounds[1, 1],
    magnet_bounds[2, 0], magnet_bounds[2, 1],
])

# Add magnet to scene
plotter.add_mesh(
    magnet_mesh,
    color='lightblue',
    opacity=0.3,
    label='Magnet (10×10×4mm)',
    show_edges=True,
    edge_color='blue',
    line_width=2,
)

# Create seed points for streamlines
# Use a circle of points above the magnet
n_seeds = 30
theta = np.linspace(0, 2*np.pi, n_seeds)
radius = 0.008  # 8mm radius circle
z_seed = 0.010  # 10mm above center

seed_points = np.column_stack([
    radius * np.cos(theta),
    radius * np.sin(theta),
    np.full(n_seeds, z_seed),
])

# Also add seeds below the magnet
seed_points_below = seed_points.copy()
seed_points_below[:, 2] = -z_seed

all_seeds = np.vstack([seed_points, seed_points_below])

print(f"  Generating streamlines from {len(all_seeds)} seed points...")

# Generate streamlines
streamlines = mesh.streamlines(
    vectors='B',
    source_center=(0, 0, 0),
    source_radius=0.015,  # 15mm radius
    n_points=100,
    max_time=0.5,
    integration_direction='both',
)

# If streamlines are generated, add them to the plot
if streamlines.n_points > 0:
    print(f"  Generated {streamlines.n_lines} streamlines")

    # Add streamlines with tubes
    plotter.add_mesh(
        streamlines.tube(radius=0.0001),  # 0.1mm radius tubes
        scalars='B_magnitude',
        cmap='plasma',
        opacity=0.8,
        label='Field lines',
        scalar_bar_args={
            'title': 'B-field magnitude (T)',
            'title_font_size': 12,
            'label_font_size': 10,
            'n_labels': 5,
            'fmt': '%.2e',
        },
    )
else:
    print("  Warning: No streamlines generated")

# Add axes
plotter.add_axes(
    xlabel='X (m)',
    ylabel='Y (m)',
    zlabel='Z (m)',
    line_width=3,
)

# Add title
plotter.add_text(
    'B-field from Cuboid Magnet (10×10×4mm, 1T z-polarization)',
    position='upper_left',
    font_size=12,
    color='black',
)

# Set camera position for good initial view
plotter.camera_position = [
    (0.08, 0.08, 0.08),  # Camera position
    (0, 0, 0),            # Focal point
    (0, 0, 1),            # View up
]

# Show the plot
print("\nOpening interactive 3D viewer...")
print("  - Left mouse: Rotate")
print("  - Right mouse: Zoom")
print("  - Middle mouse: Pan")
print("  - 'q': Quit")
print("  - 's': Save screenshot\n")

plotter.show()
